### List all messages
GET http://localhost:3000/messages

### Create a new message
POST http://localhost:3000/messages
accept: application/json
content-type: application/json 

{
  "content": "Working on NestJS"
}


### Get a particular message 
GET http://localhost:3000/messages/ba18fab6-304f-49ab-8cd0-61390970de95


